### ISSUE TITLE
Standardize naming

### ISSUE THREAD

**Issue by jchodera** [choderalab/cluster-utils#2]
We have `cluster-utils` and `cluster_utils`.  Is this general enough to be `clusterutils`?  Or `torqueutils`?

**Comment by danielparton** [comment]
I like `clusterutils` - I'll change it to that?

**Comment by kyleabeauchamp** [comment]
+1

**Comment by jchodera** [comment]
Go for it!

**Comment by Lnaden** [comment]
This is just `clusterutils` now since it is multi-cluster.
