### ISSUE TITLE
Debug issues with very many processes

### ISSUE THREAD

**Issue by jchodera** [choderalab/cluster-utils#5]
When many processes are requested, failures like this are often encountered:

```
[proxy:0:3@gpu-1-4.local] HYDU_create_process (./utils/launch/launch.c:69): execvp error on file 3 (No such file or directory)
```

I suspect this has something to do with malformed `configfile`s, potentially involving line length limits.

**Comment by Lnaden** [comment]
Closing this due to its age and the changes to the script since.
